@base_url = http://localhost:7000/api

###

# Get single booking
GET {{base_url}}/Bookings/1
Accept: application/json

###

# Get single booking - 404 not found
GET {{base_url}}/Bookings/123123123
Accept: application/json

###

# Get bookings by Guest Id
GET {{base_url}}/Bookings/guest/1
Accept: application/json

###
# Get bookings by Guest Email and Last name
GET {{base_url}}/Bookings/guest?email=test@test.com&lastname=test
Accept: application/json

###