@base_url = http://localhost:7000/api

###

# Get single booking
GET {{base_url}}/Bookings/1
Accept: application/json

###

# Get single booking - 404 not found
GET {{base_url}}/Bookings/123123123
Accept: application/json

###

# Get bookings by Guest Id
GET {{base_url}}/Bookings/guest/1
Accept: application/json

###
# Get bookings by Guest Email and Last name
GET {{base_url}}/Bookings/guest?email=guest1@guest.com&lastname=one
Accept: application/json

###

# Create booking (Guest 1)
POST {{base_url}}/Bookings
Content-Type: application/json

{
  "guest": {
    "email": "guest1@guest.com",
    "firstName": "Guest",
    "lastName": "One",
    "companyName": "test company",
    "country": "United States",
    "address": "123 Test Dr.",
    "City": "Testville",
    "State": "Ca",
    "Zip": "12345",
    "Phone": "1234567890"
  },
  "bookingRooms": [
    {
      "roomId": 1,
      "checkInDate": "2024-01-20T20:42:25.238Z",
      "checkOutDate": "2024-01-21T20:42:25.238Z",
      "numGuests": 2,
      "extraServiceIds": [
        1, 2
      ]
    },
    {
      "roomId": 2,
      "checkInDate": "2024-01-20T20:42:25.238Z",
      "checkOutDate": "2024-01-22T20:42:25.238Z",
      "numGuests": 2,
      "extraServiceIds": [
        1, 3
      ]
    }
  ],
  "paymentMethodId": 1,
  "orderNotes": "This is a test booking"
}

###

# Create booking (Guest 2)
POST {{base_url}}/Bookings
Content-Type: application/json

{
  "guest": {
    "email": "Guest2@guest.com",
    "firstName": "Guest",
    "lastName": "Two",
    "companyName": "test company",
    "country": "United States",
    "address": "123 Test Dr.",
    "City": "Testville",
    "State": "Ca",
    "Zip": "12345",
    "Phone": "1234567890"
  },
  "bookingRooms": [
    {
      "roomId": 1,
      "checkInDate": "2024-01-20T20:42:25.238Z",
      "checkOutDate": "2024-01-21T20:42:25.238Z",
      "numGuests": 2,
      "extraServiceIds": [
        1, 2
      ]
    },
    {
      "roomId": 2,
      "checkInDate": "2024-01-20T20:42:25.238Z",
      "checkOutDate": "2024-01-22T20:42:25.238Z",
      "numGuests": 2,
      "extraServiceIds": [
        1, 3
      ]
    }
  ],
  "paymentMethodId": 1,
  "orderNotes": "This is a test booking"
}

###